/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author DRAGKOZ
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jBsaveeditar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtn_Fist = new javax.swing.JButton();
        jbtn_previus = new javax.swing.JButton();
        jbtn_next = new javax.swing.JButton();
        jbtn_last = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlb_Nombre = new javax.swing.JLabel();
        jlb_RFC = new javax.swing.JLabel();
        jlb_Calle = new javax.swing.JLabel();
        jlb_No = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlb_Ciudad = new javax.swing.JLabel();
        jlb_Estado = new javax.swing.JLabel();
        jlb_Contacto = new javax.swing.JLabel();
        jlb_Telefono = new javax.swing.JLabel();
        jlb_EMail = new javax.swing.JLabel();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_RFC = new javax.swing.JTextField();
        jtf_Calle = new javax.swing.JTextField();
        jtf_Colonia = new javax.swing.JTextField();
        jtf_Ciudad = new javax.swing.JTextField();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Contacto = new javax.swing.JTextField();
        jtf_EMail = new javax.swing.JTextField();
        jtf_Telefono = new javax.swing.JTextField();
        jtf_No = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jlb_Nombre1 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(424, 324));
        setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Botton", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 153)))); // NOI18N
        jPanel5.setOpaque(false);

        jbtn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr2.png"))); // NOI18N
        jbtn_agregar.setText("Agregar");
        jbtn_agregar.setBorder(null);
        jbtn_agregar.setBorderPainted(false);
        jbtn_agregar.setContentAreaFilled(false);
        jbtn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_agregar.setIconTextGap(-3);
        jbtn_agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr3.png"))); // NOI18N
        jbtn_agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr1.png"))); // NOI18N
        jbtn_agregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del2.png"))); // NOI18N
        jbtn_borrar.setText("Borrar");
        jbtn_borrar.setBorder(null);
        jbtn_borrar.setBorderPainted(false);
        jbtn_borrar.setContentAreaFilled(false);
        jbtn_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_borrar.setIconTextGap(-3);
        jbtn_borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del3.png"))); // NOI18N
        jbtn_borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del1.png"))); // NOI18N
        jbtn_borrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbtn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav2.png"))); // NOI18N
        jbtn_guardar.setText("Save");
        jbtn_guardar.setBorder(null);
        jbtn_guardar.setBorderPainted(false);
        jbtn_guardar.setContentAreaFilled(false);
        jbtn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_guardar.setIconTextGap(-3);
        jbtn_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav3.png"))); // NOI18N
        jbtn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav1.png"))); // NOI18N
        jbtn_guardar.setVerifyInputWhenFocusTarget(false);
        jbtn_guardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbtn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed2.png"))); // NOI18N
        jbtn_editar.setText(" Editar");
        jbtn_editar.setBorder(null);
        jbtn_editar.setBorderPainted(false);
        jbtn_editar.setContentAreaFilled(false);
        jbtn_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_editar.setIconTextGap(-3);
        jbtn_editar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed3.png"))); // NOI18N
        jbtn_editar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed1.png"))); // NOI18N
        jbtn_editar.setVerifyInputWhenFocusTarget(false);
        jbtn_editar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBsaveeditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.png"))); // NOI18N
        jBsaveeditar1.setText("Save Edit");
        jBsaveeditar1.setBorder(null);
        jBsaveeditar1.setBorderPainted(false);
        jBsaveeditar1.setContentAreaFilled(false);
        jBsaveeditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsaveeditar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBsaveeditar1.setIconTextGap(-3);
        jBsaveeditar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N
        jBsaveeditar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.png"))); // NOI18N
        jBsaveeditar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBsaveeditar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_borrar)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_editar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBsaveeditar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jbtn_agregar)))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jbtn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBsaveeditar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_borrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jbtn_guardar)
                .addContainerGap())
        );

        add(jPanel5);
        jPanel5.setBounds(380, 10, 250, 260);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navegacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jbtn_Fist.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_Fist.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_Fist.setText("|<");
        jbtn_Fist.setActionCommand("");
        jbtn_Fist.setBorder(null);
        jbtn_Fist.setContentAreaFilled(false);
        jbtn_Fist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Fist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_previus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_previus.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_previus.setText("<");
        jbtn_previus.setActionCommand("");
        jbtn_previus.setBorder(null);
        jbtn_previus.setContentAreaFilled(false);
        jbtn_previus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_previus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_next.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_next.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_next.setText(">");
        jbtn_next.setActionCommand("");
        jbtn_next.setBorder(null);
        jbtn_next.setContentAreaFilled(false);
        jbtn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_last.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_last.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_last.setText(">|");
        jbtn_last.setActionCommand("");
        jbtn_last.setBorder(null);
        jbtn_last.setContentAreaFilled(false);
        jbtn_last.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_last.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtn_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtn_previus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jbtn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_previus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(10, 270, 360, 80);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setOpaque(false);

        jlb_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre.setText("NOMBRE:");

        jlb_RFC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_RFC.setForeground(new java.awt.Color(0, 0, 102));
        jlb_RFC.setText("RFC:");

        jlb_Calle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Calle.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Calle.setText("CALLE:");

        jlb_No.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_No.setForeground(new java.awt.Color(0, 0, 102));
        jlb_No.setText("NO.");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("COLONIA:");

        jlb_Ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Ciudad.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Ciudad.setText("CIUDAD:");

        jlb_Estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Estado.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Estado.setText("ESTADO:");

        jlb_Contacto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Contacto.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Contacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_Contacto.setText("CONTACTO:");
        jlb_Contacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlb_Telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Telefono.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Telefono.setText("TELEFONO:");

        jlb_EMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_EMail.setForeground(new java.awt.Color(0, 0, 102));
        jlb_EMail.setText("E-MAIL:");

        jtf_Nombre.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_RFC.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Calle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Colonia.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Ciudad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Estado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Contacto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_EMail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Telefono.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_No.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtf_No, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jtf_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jlb_Nombre)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jlb_RFC)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jlb_Calle)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jlb_No)
                            .addGap(119, 119, 119)
                            .addComponent(jtf_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jlb_Ciudad)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jlb_Estado)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_Contacto)
                            .addGap(4, 4, 4)
                            .addComponent(jtf_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Telefono))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jlb_EMail)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Nombre))
                        .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_RFC))
                        .addComponent(jtf_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Calle))
                        .addComponent(jtf_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_No)))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Ciudad))
                        .addComponent(jtf_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Estado))
                        .addComponent(jtf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlb_Contacto))
                        .addComponent(jtf_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addComponent(jlb_Telefono)
                    .addGap(12, 12, 12)
                    .addComponent(jlb_EMail)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1);
        jPanel1.setBounds(10, 10, 360, 260);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setFocusable(false);
        jLabel11.setRequestFocusEnabled(false);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        add(jLabel11);
        jLabel11.setBounds(0, 0, 350, 270);

        jlb_Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre1.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre1.setText("ID:");
        add(jlb_Nombre1);
        jlb_Nombre1.setBounds(420, 300, 30, 20);

        jtf_id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_id);
        jtf_id.setBounds(450, 300, 80, 20);

        jbtn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bs3.png"))); // NOI18N
        jbtn_buscar.setToolTipText("");
        jbtn_buscar.setBorderPainted(false);
        jbtn_buscar.setContentAreaFilled(false);
        jbtn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jbtn_buscar);
        jbtn_buscar.setBounds(550, 280, 60, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBsaveeditar1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JButton jbtn_Fist;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_borrar;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_editar;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_last;
    public javax.swing.JButton jbtn_next;
    public javax.swing.JButton jbtn_previus;
    public javax.swing.JLabel jlb_Calle;
    public javax.swing.JLabel jlb_Ciudad;
    public javax.swing.JLabel jlb_Contacto;
    public javax.swing.JLabel jlb_EMail;
    public javax.swing.JLabel jlb_Estado;
    public javax.swing.JLabel jlb_No;
    public javax.swing.JLabel jlb_Nombre;
    public javax.swing.JLabel jlb_Nombre1;
    public javax.swing.JLabel jlb_RFC;
    public javax.swing.JLabel jlb_Telefono;
    public javax.swing.JTextField jtf_Calle;
    public javax.swing.JTextField jtf_Ciudad;
    public javax.swing.JTextField jtf_Colonia;
    public javax.swing.JTextField jtf_Contacto;
    public javax.swing.JTextField jtf_EMail;
    public javax.swing.JTextField jtf_Estado;
    public javax.swing.JTextField jtf_No;
    public javax.swing.JTextField jtf_Nombre;
    public javax.swing.JTextField jtf_RFC;
    public javax.swing.JTextField jtf_Telefono;
    public javax.swing.JTextField jtf_id;
    // End of variables declaration//GEN-END:variables
}
