/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author DRAGKOZ
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Nombre = new javax.swing.JLabel();
        jlb_RFC = new javax.swing.JLabel();
        jlb_Calle = new javax.swing.JLabel();
        jlb_No = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlb_Ciudad = new javax.swing.JLabel();
        jlb_Estado = new javax.swing.JLabel();
        jlb_Contacto = new javax.swing.JLabel();
        jlb_Telefono = new javax.swing.JLabel();
        jlb_EMail = new javax.swing.JLabel();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_RFC = new javax.swing.JTextField();
        jtf_Calle = new javax.swing.JTextField();
        jtf_Colonia = new javax.swing.JTextField();
        jtf_Ciudad = new javax.swing.JTextField();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Contacto = new javax.swing.JTextField();
        jtf_EMail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_Clean = new javax.swing.JButton();
        jbtn_search = new javax.swing.JButton();
        jbtn_Save = new javax.swing.JButton();
        jbtn_Delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtn_Fist = new javax.swing.JButton();
        jbtn_previus = new javax.swing.JButton();
        jbtn_next = new javax.swing.JButton();
        jbtn_last = new javax.swing.JButton();
        jtf_No = new javax.swing.JFormattedTextField();
        jtf_Telefono = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(424, 324));
        setLayout(null);

        jlb_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre.setText("NOMBRE:");
        add(jlb_Nombre);
        jlb_Nombre.setBounds(24, 13, 67, 17);

        jlb_RFC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_RFC.setForeground(new java.awt.Color(0, 0, 102));
        jlb_RFC.setText("RFC:");
        add(jlb_RFC);
        jlb_RFC.setBounds(58, 40, 33, 17);

        jlb_Calle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Calle.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Calle.setText("CALLE:");
        add(jlb_Calle);
        jlb_Calle.setBounds(43, 67, 48, 17);

        jlb_No.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_No.setForeground(new java.awt.Color(0, 0, 102));
        jlb_No.setText("NO.");
        add(jlb_No);
        jlb_No.setBounds(66, 96, 25, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("COLONIA:");
        add(jLabel5);
        jLabel5.setBounds(139, 96, 67, 17);

        jlb_Ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Ciudad.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Ciudad.setText("CIUDAD:");
        add(jlb_Ciudad);
        jlb_Ciudad.setBounds(34, 123, 57, 17);

        jlb_Estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Estado.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Estado.setText("ESTADO:");
        add(jlb_Estado);
        jlb_Estado.setBounds(31, 150, 60, 17);

        jlb_Contacto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Contacto.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Contacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_Contacto.setText("CONTACTO:");
        jlb_Contacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jlb_Contacto);
        jlb_Contacto.setBounds(10, 177, 81, 17);

        jlb_Telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Telefono.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Telefono.setText("TELEFONO:");
        add(jlb_Telefono);
        jlb_Telefono.setBounds(12, 204, 79, 17);

        jlb_EMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_EMail.setForeground(new java.awt.Color(0, 0, 102));
        jlb_EMail.setText("E-MAIL:");
        add(jlb_EMail);
        jlb_EMail.setBounds(37, 233, 52, 17);

        jtf_Nombre.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Nombre);
        jtf_Nombre.setBounds(95, 11, 250, 21);

        jtf_RFC.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_RFC);
        jtf_RFC.setBounds(95, 38, 250, 21);

        jtf_Calle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Calle);
        jtf_Calle.setBounds(95, 65, 250, 21);

        jtf_Colonia.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Colonia);
        jtf_Colonia.setBounds(210, 94, 135, 21);

        jtf_Ciudad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Ciudad);
        jtf_Ciudad.setBounds(95, 121, 143, 21);

        jtf_Estado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Estado);
        jtf_Estado.setBounds(95, 148, 143, 21);

        jtf_Contacto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_Contacto);
        jtf_Contacto.setBounds(95, 175, 250, 21);

        jtf_EMail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        add(jtf_EMail);
        jtf_EMail.setBounds(100, 230, 143, 21);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbtn_Clean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/limpiar.png"))); // NOI18N
        jbtn_Clean.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtn_Clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar.png"))); // NOI18N
        jbtn_search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/guardar.png"))); // NOI18N
        jbtn_Save.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtn_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eliminar.png"))); // NOI18N
        jbtn_Delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtn_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Clean, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(351, 0, 80, 306);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jbtn_Fist.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_Fist.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_Fist.setText("|<");
        jbtn_Fist.setActionCommand("");
        jbtn_Fist.setBorder(null);
        jbtn_Fist.setContentAreaFilled(false);
        jbtn_Fist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Fist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_previus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_previus.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_previus.setText("<");
        jbtn_previus.setActionCommand("");
        jbtn_previus.setBorder(null);
        jbtn_previus.setContentAreaFilled(false);
        jbtn_previus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_previus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_next.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_next.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_next.setText(">");
        jbtn_next.setActionCommand("");
        jbtn_next.setBorder(null);
        jbtn_next.setContentAreaFilled(false);
        jbtn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_last.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_last.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_last.setText(">|");
        jbtn_last.setActionCommand("");
        jbtn_last.setBorder(null);
        jbtn_last.setContentAreaFilled(false);
        jbtn_last.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_last.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtn_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtn_previus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_previus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(0, 270, 345, 65);

        jtf_No.setForeground(new java.awt.Color(0, 0, 102));
        jtf_No.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        add(jtf_No);
        jtf_No.setBounds(100, 90, 30, 20);

        jtf_Telefono.setForeground(new java.awt.Color(0, 0, 102));
        jtf_Telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        add(jtf_Telefono);
        jtf_Telefono.setBounds(100, 200, 140, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setFocusable(false);
        jLabel11.setRequestFocusEnabled(false);
        jLabel11.setVerifyInputWhenFocusTarget(false);
        add(jLabel11);
        jLabel11.setBounds(0, 0, 350, 270);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JButton jbtn_Clean;
    public javax.swing.JButton jbtn_Delete;
    public javax.swing.JButton jbtn_Fist;
    public javax.swing.JButton jbtn_Save;
    public javax.swing.JButton jbtn_last;
    public javax.swing.JButton jbtn_next;
    public javax.swing.JButton jbtn_previus;
    public javax.swing.JButton jbtn_search;
    public javax.swing.JLabel jlb_Calle;
    public javax.swing.JLabel jlb_Ciudad;
    public javax.swing.JLabel jlb_Contacto;
    public javax.swing.JLabel jlb_EMail;
    public javax.swing.JLabel jlb_Estado;
    public javax.swing.JLabel jlb_No;
    public javax.swing.JLabel jlb_Nombre;
    public javax.swing.JLabel jlb_RFC;
    public javax.swing.JLabel jlb_Telefono;
    public javax.swing.JTextField jtf_Calle;
    public javax.swing.JTextField jtf_Ciudad;
    public javax.swing.JTextField jtf_Colonia;
    public javax.swing.JTextField jtf_Contacto;
    public javax.swing.JTextField jtf_EMail;
    public javax.swing.JTextField jtf_Estado;
    public javax.swing.JFormattedTextField jtf_No;
    public javax.swing.JTextField jtf_Nombre;
    public javax.swing.JTextField jtf_RFC;
    public javax.swing.JFormattedTextField jtf_Telefono;
    // End of variables declaration//GEN-END:variables
}
