/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ViewOperacionesCompras extends javax.swing.JPanel {

    /**
     * Creates new form ViewOperacionesCompras
     */
    public ViewOperacionesCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localeEditor1 = new com.toedter.components.LocaleEditor();
        compras = new javax.swing.JPanel();
        formulario = new javax.swing.JPanel();
        jlb_proveedor = new javax.swing.JLabel();
        jlb_producto = new javax.swing.JLabel();
        jcbx_proveedor = new javax.swing.JComboBox();
        jcbx_producto = new javax.swing.JComboBox();
        jlb_cantidad = new javax.swing.JLabel();
        jsp_cantidad = new javax.swing.JSpinner();
        jbtn_agregar = new javax.swing.JButton();
        jlb_Nombre1 = new javax.swing.JLabel();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        jlb_iva = new javax.swing.JLabel();
        jtf_iva = new javax.swing.JTextField();
        Detalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_detalle = new javax.swing.JTable();
        jlb_total = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jlb_idCompra = new javax.swing.JLabel();
        jtf_idCompra = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        controles = new javax.swing.JPanel();
        jbtn_nvaCompra = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jlb_consultar = new javax.swing.JLabel();
        jcbx_consultar = new javax.swing.JComboBox();
        jbtn_consultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        compras.setBackground(new java.awt.Color(255, 255, 255));
        compras.setMinimumSize(new java.awt.Dimension(797, 340));

        formulario.setBackground(new java.awt.Color(255, 255, 255));
        formulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        formulario.setOpaque(false);

        jlb_proveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_proveedor.setForeground(new java.awt.Color(0, 0, 102));
        jlb_proveedor.setText("Proveedor");

        jlb_producto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_producto.setForeground(new java.awt.Color(0, 0, 102));
        jlb_producto.setText("Producto");

        jcbx_proveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbx_proveedor.setForeground(new java.awt.Color(0, 0, 153));
        jcbx_proveedor.setEnabled(false);

        jcbx_producto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbx_producto.setForeground(new java.awt.Color(0, 0, 153));
        jcbx_producto.setEnabled(false);

        jlb_cantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_cantidad.setForeground(new java.awt.Color(0, 0, 102));
        jlb_cantidad.setText("Cantidad");

        jsp_cantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jsp_cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jsp_cantidad.setEnabled(false);

        jbtn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_agregar.setForeground(new java.awt.Color(0, 0, 153));
        jbtn_agregar.setText("AGREGAR");
        jbtn_agregar.setToolTipText("AGREGAR");
        jbtn_agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        jbtn_agregar.setEnabled(false);

        jlb_Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre1.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre1.setText("Fecha");

        jdc_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jdc_fecha.setForeground(new java.awt.Color(0, 0, 153));
        jdc_fecha.setDateFormatString("yyyy-MM-dd");
        jdc_fecha.setEnabled(false);
        jdc_fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jlb_iva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_iva.setForeground(new java.awt.Color(0, 0, 102));
        jlb_iva.setText("IVA");

        jtf_iva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtf_iva.setForeground(new java.awt.Color(0, 0, 153));
        jtf_iva.setEnabled(false);

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlb_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbx_producto, 0, 124, Short.MAX_VALUE)
                    .addComponent(jcbx_proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addComponent(jlb_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlb_iva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_iva)
                        .addGap(10, 10, 10))
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addComponent(jlb_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsp_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addGap(5, 5, 5))))
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_proveedor)
                        .addComponent(jcbx_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlb_Nombre1))
                    .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_iva)
                        .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbx_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_producto)
                    .addComponent(jlb_cantidad)
                    .addComponent(jsp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_agregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Detalle.setBackground(new java.awt.Color(255, 255, 255));

        jtb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Precio", "Precio IVA", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jtb_detalle);

        jlb_total.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_total.setForeground(new java.awt.Color(0, 0, 102));
        jlb_total.setText("TOTAL");

        jtf_total.setDisabledTextColor(new java.awt.Color(0, 0, 153));
        jtf_total.setEnabled(false);
        jtf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_totalActionPerformed(evt);
            }
        });

        jlb_idCompra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_idCompra.setForeground(new java.awt.Color(0, 0, 102));
        jlb_idCompra.setText("ID de compra");

        jtf_idCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idCompraActionPerformed(evt);
            }
        });

        jbtn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_buscar.setForeground(new java.awt.Color(0, 0, 153));
        jbtn_buscar.setText("BUSCAR");
        jbtn_buscar.setToolTipText("Nueva Compra");
        jbtn_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        jbtn_buscar.setMinimumSize(new java.awt.Dimension(100, 20));
        jbtn_buscar.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout DetalleLayout = new javax.swing.GroupLayout(Detalle);
        Detalle.setLayout(DetalleLayout);
        DetalleLayout.setHorizontalGroup(
            DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_idCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_idCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlb_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DetalleLayout.setVerticalGroup(
            DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetalleLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_total)
                    .addComponent(jlb_idCompra)
                    .addComponent(jtf_idCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        controles.setBackground(new java.awt.Color(255, 255, 255));
        controles.setOpaque(false);

        jbtn_nvaCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_nvaCompra.setForeground(new java.awt.Color(0, 0, 153));
        jbtn_nvaCompra.setText("Nueva Compra");
        jbtn_nvaCompra.setToolTipText("Nueva Compra");
        jbtn_nvaCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        jbtn_nvaCompra.setMinimumSize(new java.awt.Dimension(100, 20));
        jbtn_nvaCompra.setPreferredSize(new java.awt.Dimension(100, 20));

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_cancelar.setForeground(new java.awt.Color(0, 0, 153));
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.setToolTipText("Nueva Compra");
        jbtn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        jbtn_cancelar.setEnabled(false);
        jbtn_cancelar.setMinimumSize(new java.awt.Dimension(100, 20));
        jbtn_cancelar.setPreferredSize(new java.awt.Dimension(100, 20));

        jlb_consultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_consultar.setForeground(new java.awt.Color(0, 0, 102));
        jlb_consultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_consultar.setText("CONSULTAR");

        jcbx_consultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbx_consultar.setForeground(new java.awt.Color(0, 0, 153));
        jcbx_consultar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODAS", "-----------------" }));
        jcbx_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_consultarActionPerformed(evt);
            }
        });

        jbtn_consultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_consultar.setForeground(new java.awt.Color(0, 0, 153));
        jbtn_consultar.setText("IR");
        jbtn_consultar.setToolTipText("Nueva Compra");
        jbtn_consultar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.darkGray));
        jbtn_consultar.setMinimumSize(new java.awt.Dimension(100, 20));
        jbtn_consultar.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout controlesLayout = new javax.swing.GroupLayout(controles);
        controles.setLayout(controlesLayout);
        controlesLayout.setHorizontalGroup(
            controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_nvaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(controlesLayout.createSequentialGroup()
                        .addComponent(jcbx_consultar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlesLayout.setVerticalGroup(
            controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_nvaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbx_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout comprasLayout = new javax.swing.GroupLayout(compras);
        compras.setLayout(comprasLayout);
        comprasLayout.setHorizontalGroup(
            comprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Detalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comprasLayout.createSequentialGroup()
                        .addComponent(formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        comprasLayout.setVerticalGroup(
            comprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Detalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_totalActionPerformed

    private void jcbx_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_consultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_consultarActionPerformed

    private void jtf_idCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Detalle;
    public javax.swing.JPanel compras;
    public javax.swing.JPanel controles;
    public javax.swing.JPanel formulario;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_cancelar;
    public javax.swing.JButton jbtn_consultar;
    public javax.swing.JButton jbtn_nvaCompra;
    public javax.swing.JComboBox jcbx_consultar;
    public javax.swing.JComboBox jcbx_producto;
    public javax.swing.JComboBox jcbx_proveedor;
    public com.toedter.calendar.JDateChooser jdc_fecha;
    public javax.swing.JLabel jlb_Nombre1;
    public javax.swing.JLabel jlb_cantidad;
    public javax.swing.JLabel jlb_consultar;
    public javax.swing.JLabel jlb_idCompra;
    public javax.swing.JLabel jlb_iva;
    public javax.swing.JLabel jlb_producto;
    public javax.swing.JLabel jlb_proveedor;
    public javax.swing.JLabel jlb_total;
    public javax.swing.JSpinner jsp_cantidad;
    public javax.swing.JTable jtb_detalle;
    public javax.swing.JTextField jtf_idCompra;
    public javax.swing.JTextField jtf_iva;
    public javax.swing.JTextField jtf_total;
    private com.toedter.components.LocaleEditor localeEditor1;
    // End of variables declaration//GEN-END:variables
}
