/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author DRAGKOZ
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
        /*
        RestrictedTextField idR = new RestrictedTextField(jtf_id);
        RestrictedTextField noR = new RestrictedTextField(jtf_No);
        RestrictedTextField telefonoR = new RestrictedTextField(jtf_Telefono);
        idR.setLimit(4);
        noR.setLimit(3);
        telefonoR.setLimit(10);
        
        idR.setOnlyNums(true);
        noR.setOnlyNums(true);
        telefonoR.setOnlyNums(true);
        
        idR.setAcceptSpace(false);
        noR.setAcceptSpace(false);
        telefonoR.setAcceptSpace(false);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        proveedores = new javax.swing.JPanel();
        comandos = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jbtn_saveEdit = new javax.swing.JButton();
        navegacion = new javax.swing.JPanel();
        jbtn_Fist = new javax.swing.JButton();
        jbtn_previus = new javax.swing.JButton();
        jbtn_next = new javax.swing.JButton();
        jbtn_last = new javax.swing.JButton();
        formulario = new javax.swing.JPanel();
        jlb_Nombre = new javax.swing.JLabel();
        jlb_RFC = new javax.swing.JLabel();
        jlb_Calle = new javax.swing.JLabel();
        jlb_No = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlb_Ciudad = new javax.swing.JLabel();
        jlb_Estado = new javax.swing.JLabel();
        jlb_Contacto = new javax.swing.JLabel();
        jlb_Telefono = new javax.swing.JLabel();
        jlb_EMail = new javax.swing.JLabel();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_RFC = new javax.swing.JTextField();
        jtf_Calle = new javax.swing.JTextField();
        jtf_Colonia = new javax.swing.JTextField();
        jtf_Ciudad = new javax.swing.JTextField();
        jtf_Estado = new javax.swing.JTextField();
        jtf_Contacto = new javax.swing.JTextField();
        jtf_EMail = new javax.swing.JTextField();
        jtf_Telefono = new javax.swing.JTextField();
        jtf_No = new javax.swing.JTextField();
        buscar = new javax.swing.JPanel();
        jlb_Nombre1 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtble_detalle = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(812, 615));
        setPreferredSize(new java.awt.Dimension(812, 615));

        proveedores.setBackground(new java.awt.Color(255, 255, 255));
        proveedores.setMaximumSize(new java.awt.Dimension(1600, 1230));
        proveedores.setMinimumSize(new java.awt.Dimension(812, 615));
        proveedores.setOpaque(false);

        comandos.setBackground(new java.awt.Color(255, 255, 255));
        comandos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Botton", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 153)), "Comandos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        comandos.setOpaque(false);

        jbtn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr2.png"))); // NOI18N
        jbtn_agregar.setText("Agregar");
        jbtn_agregar.setBorder(null);
        jbtn_agregar.setBorderPainted(false);
        jbtn_agregar.setContentAreaFilled(false);
        jbtn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_agregar.setIconTextGap(-3);
        jbtn_agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr3.png"))); // NOI18N
        jbtn_agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/agr1.png"))); // NOI18N
        jbtn_agregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del2.png"))); // NOI18N
        jbtn_borrar.setText("Borrar");
        jbtn_borrar.setBorder(null);
        jbtn_borrar.setBorderPainted(false);
        jbtn_borrar.setContentAreaFilled(false);
        jbtn_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_borrar.setIconTextGap(-3);
        jbtn_borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del3.png"))); // NOI18N
        jbtn_borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del1.png"))); // NOI18N
        jbtn_borrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbtn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav2.png"))); // NOI18N
        jbtn_guardar.setText("Save");
        jbtn_guardar.setBorder(null);
        jbtn_guardar.setBorderPainted(false);
        jbtn_guardar.setContentAreaFilled(false);
        jbtn_guardar.setEnabled(false);
        jbtn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_guardar.setIconTextGap(-3);
        jbtn_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav3.png"))); // NOI18N
        jbtn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sav1.png"))); // NOI18N
        jbtn_guardar.setVerifyInputWhenFocusTarget(false);
        jbtn_guardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbtn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed2.png"))); // NOI18N
        jbtn_editar.setText(" Editar");
        jbtn_editar.setBorder(null);
        jbtn_editar.setBorderPainted(false);
        jbtn_editar.setContentAreaFilled(false);
        jbtn_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_editar.setIconTextGap(-3);
        jbtn_editar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed3.png"))); // NOI18N
        jbtn_editar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed1.png"))); // NOI18N
        jbtn_editar.setVerifyInputWhenFocusTarget(false);
        jbtn_editar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbtn_saveEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.png"))); // NOI18N
        jbtn_saveEdit.setText("Save Edit");
        jbtn_saveEdit.setBorder(null);
        jbtn_saveEdit.setBorderPainted(false);
        jbtn_saveEdit.setContentAreaFilled(false);
        jbtn_saveEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_saveEdit.setEnabled(false);
        jbtn_saveEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_saveEdit.setIconTextGap(-3);
        jbtn_saveEdit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N
        jbtn_saveEdit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.png"))); // NOI18N
        jbtn_saveEdit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtn_saveEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_saveEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comandosLayout = new javax.swing.GroupLayout(comandos);
        comandos.setLayout(comandosLayout);
        comandosLayout.setHorizontalGroup(
            comandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(comandosLayout.createSequentialGroup()
                        .addComponent(jbtn_borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jbtn_saveEdit))
                    .addGroup(comandosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(comandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_editar)
                            .addComponent(jbtn_guardar))))
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jbtn_agregar)
                .addContainerGap())
        );
        comandosLayout.setVerticalGroup(
            comandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comandosLayout.createSequentialGroup()
                .addComponent(jbtn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(comandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_saveEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_borrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addComponent(jbtn_guardar))
        );

        navegacion.setBackground(new java.awt.Color(255, 255, 255));
        navegacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navegacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        navegacion.setOpaque(false);

        jbtn_Fist.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_Fist.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_Fist.setText("|<");
        jbtn_Fist.setActionCommand("");
        jbtn_Fist.setBorder(null);
        jbtn_Fist.setContentAreaFilled(false);
        jbtn_Fist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Fist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_previus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_previus.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_previus.setText("<");
        jbtn_previus.setActionCommand("");
        jbtn_previus.setBorder(null);
        jbtn_previus.setContentAreaFilled(false);
        jbtn_previus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_previus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_next.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_next.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_next.setText(">");
        jbtn_next.setActionCommand("");
        jbtn_next.setBorder(null);
        jbtn_next.setContentAreaFilled(false);
        jbtn_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbtn_last.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn_last.setForeground(new java.awt.Color(0, 0, 102));
        jbtn_last.setText(">|");
        jbtn_last.setActionCommand("");
        jbtn_last.setBorder(null);
        jbtn_last.setContentAreaFilled(false);
        jbtn_last.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_last.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout navegacionLayout = new javax.swing.GroupLayout(navegacion);
        navegacion.setLayout(navegacionLayout);
        navegacionLayout.setHorizontalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jbtn_Fist, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jbtn_previus, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jbtn_next, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jbtn_last, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        navegacionLayout.setVerticalGroup(
            navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegacionLayout.createSequentialGroup()
                .addGroup(navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Fist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_previus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        formulario.setOpaque(false);

        jlb_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre.setText("NOMBRE:");

        jlb_RFC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_RFC.setForeground(new java.awt.Color(0, 0, 102));
        jlb_RFC.setText("RFC:");

        jlb_Calle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Calle.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Calle.setText("CALLE:");

        jlb_No.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_No.setForeground(new java.awt.Color(0, 0, 102));
        jlb_No.setText("NO.");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("COLONIA:");

        jlb_Ciudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Ciudad.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Ciudad.setText("CIUDAD:");

        jlb_Estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Estado.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Estado.setText("ESTADO:");

        jlb_Contacto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Contacto.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Contacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_Contacto.setText("CONTACTO:");
        jlb_Contacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlb_Telefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Telefono.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Telefono.setText("TELEFONO:");

        jlb_EMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_EMail.setForeground(new java.awt.Color(0, 0, 102));
        jlb_EMail.setText("E-MAIL:");

        jtf_Nombre.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_RFC.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Calle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Colonia.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Ciudad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Estado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Contacto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_EMail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_Telefono.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_No.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_Telefono)
                    .addComponent(jlb_Contacto)
                    .addComponent(jlb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Ciudad)
                    .addComponent(jlb_No)
                    .addComponent(jlb_Calle)
                    .addComponent(jlb_RFC)
                    .addComponent(jlb_Nombre)
                    .addComponent(jlb_EMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addComponent(jtf_No)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Colonia))
                    .addComponent(jtf_RFC)
                    .addComponent(jtf_Nombre)
                    .addComponent(jtf_Calle)
                    .addComponent(jtf_Ciudad)
                    .addComponent(jtf_Estado)
                    .addComponent(jtf_Contacto)
                    .addComponent(jtf_Telefono)
                    .addComponent(jtf_EMail))
                .addGap(28, 28, 28))
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_Nombre)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_RFC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Calle))
                .addGap(10, 10, 10)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Ciudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Contacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_EMail)))
        );

        jlb_Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlb_Nombre1.setForeground(new java.awt.Color(0, 0, 102));
        jlb_Nombre1.setText("ID:");

        jtf_id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jbtn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bs3.png"))); // NOI18N
        jbtn_buscar.setToolTipText("");
        jbtn_buscar.setBorderPainted(false);
        jbtn_buscar.setContentAreaFilled(false);
        jbtn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_Nombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buscarLayout.createSequentialGroup()
                        .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalle de los Proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jtble_detalle.setBackground(new java.awt.Color(204, 204, 255));
        jtble_detalle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtble_detalle.setForeground(new java.awt.Color(0, 0, 102));
        jtble_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Producto", "Nombre", "RFC", "Calle", "no", "Colonia", "Ciudad", "Estado", "Contacto", "Telefono", "E-Mail"
            }
        ));
        jtble_detalle.setColumnSelectionAllowed(true);
        jtble_detalle.setGridColor(new java.awt.Color(0, 0, 102));
        jtble_detalle.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(jtble_detalle);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout proveedoresLayout = new javax.swing.GroupLayout(proveedores);
        proveedores.setLayout(proveedoresLayout);
        proveedoresLayout.setHorizontalGroup(
            proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        proveedoresLayout.setVerticalGroup(
            proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comandos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(proveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarActionPerformed

    private void jbtn_saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_saveEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_saveEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscar;
    private javax.swing.JPanel comandos;
    private javax.swing.JPanel formulario;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_Fist;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_borrar;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_editar;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_last;
    public javax.swing.JButton jbtn_next;
    public javax.swing.JButton jbtn_previus;
    public javax.swing.JButton jbtn_saveEdit;
    public javax.swing.JLabel jlb_Calle;
    public javax.swing.JLabel jlb_Ciudad;
    public javax.swing.JLabel jlb_Contacto;
    public javax.swing.JLabel jlb_EMail;
    public javax.swing.JLabel jlb_Estado;
    public javax.swing.JLabel jlb_No;
    public javax.swing.JLabel jlb_Nombre;
    public javax.swing.JLabel jlb_Nombre1;
    public javax.swing.JLabel jlb_RFC;
    public javax.swing.JLabel jlb_Telefono;
    public javax.swing.JTable jtble_detalle;
    public javax.swing.JTextField jtf_Calle;
    public javax.swing.JTextField jtf_Ciudad;
    public javax.swing.JTextField jtf_Colonia;
    public javax.swing.JTextField jtf_Contacto;
    public javax.swing.JTextField jtf_EMail;
    public javax.swing.JTextField jtf_Estado;
    public javax.swing.JTextField jtf_No;
    public javax.swing.JTextField jtf_Nombre;
    public javax.swing.JTextField jtf_RFC;
    public javax.swing.JTextField jtf_Telefono;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JPanel navegacion;
    public javax.swing.JPanel proveedores;
    // End of variables declaration//GEN-END:variables
}