/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jfile = new javax.swing.JMenu();
        jMvolumen = new javax.swing.JMenuItem();
        jMArea = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfile.setText("'");

        jMvolumen.setText("calcular Area");
        jfile.add(jMvolumen);

        jMArea.setText("calcular Volumen");
        jMArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAreaActionPerformed(evt);
            }
        });
        jfile.add(jMArea);

        jMenuBar2.add(jfile);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMAreaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem jMArea;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMvolumen;
    public javax.swing.JMenu jfile;
    // End of variables declaration//GEN-END:variables
}
