package models;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;

/**
 *
 * @author Liz
 */
public class Addchofer extends javax.swing.JFrame {

    private Connection conexion;
    private Statement st;
    private ResultSet rs;

    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/novatransporte", "root", "");
            st = conexion.createStatement();

            rs = st.executeQuery("Select * from chofer");

            rs.next();
            jTid.setText(rs.getString("id_chofer"));
            jTnombre.setText(rs.getString("nombre"));
            jTlicencia.setText(rs.getString("licencia"));
            jTseguro.setText(rs.getString("seguro"));
            jTdomicilio.setText(rs.getString("domicilio"));
            jTtelefono.setText(rs.getString("telefono"));
            jTedad.setText(rs.getString("edad"));
            jTtarjeton.setText(rs.getString("tarjeton"));
            jTasign.setText(rs.getString("asign"));

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error" + err.getMessage());
        }
    }//conectar

    public Addchofer() {
        initComponents();
        Conectar();
    }//addchofer

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLlicencia = new javax.swing.JLabel();
        jLseguro = new javax.swing.JLabel();
        jLdomicilio = new javax.swing.JLabel();
        jLtelefono = new javax.swing.JLabel();
        jLedad = new javax.swing.JLabel();
        jLtarjeton = new javax.swing.JLabel();
        jTlicencia = new javax.swing.JTextField();
        jTseguro = new javax.swing.JTextField();
        jTdomicilio = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTedad = new javax.swing.JTextField();
        jTtarjeton = new javax.swing.JTextField();
        jBregistrar = new javax.swing.JButton();
        jLasign = new javax.swing.JLabel();
        jTasign = new javax.swing.JTextField();
        jBatras = new javax.swing.JButton();
        jBatraspag = new javax.swing.JButton();
        jBsigPag = new javax.swing.JButton();
        jBsiguiente = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jLid_chofer = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jBactualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inserte un nuevo chofer!!!");

        jLnombre.setText("Nombre:");

        jLlicencia.setText("licencia");

        jLseguro.setText("seguro");

        jLdomicilio.setText("domicilio");

        jLtelefono.setText("telefono");

        jLedad.setText("edad");

        jLtarjeton.setText("tarjeton");

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jBregistrar.setText("Registrar");
        jBregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBregistrarMouseClicked(evt);
            }
        });
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        jLasign.setText("asign");

        jBatras.setText("|<");
        jBatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBatrasMouseClicked(evt);
            }
        });
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        jBatraspag.setText("<<");
        jBatraspag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBatraspagMouseClicked(evt);
            }
        });

        jBsigPag.setText(">>");
        jBsigPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsigPagMouseClicked(evt);
            }
        });

        jBsiguiente.setText(">|");
        jBsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsiguienteMouseClicked(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBborrarMouseClicked(evt);
            }
        });

        jBnuevo.setText("Nuevo");
        jBnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBnuevoMouseClicked(evt);
            }
        });
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });

        jLid_chofer.setText("id_chofer");

        jBactualizar.setText("Actualizar");
        jBactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBactualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnombre)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLseguro)
                                .addComponent(jLlicencia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLtelefono)
                                    .addComponent(jLdomicilio)
                                    .addComponent(jLedad)
                                    .addComponent(jLtarjeton)
                                    .addComponent(jLasign)))
                            .addComponent(jLid_chofer))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTedad, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTdomicilio)
                                .addComponent(jTlicencia)
                                .addComponent(jTseguro)
                                .addComponent(jTtelefono)
                                .addComponent(jTnombre)
                                .addComponent(jTtarjeton)
                                .addComponent(jTasign, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(80, 145, Short.MAX_VALUE)
                        .addComponent(jBatras)
                        .addGap(18, 18, 18)
                        .addComponent(jBatraspag)
                        .addGap(18, 18, 18)
                        .addComponent(jBsigPag)
                        .addGap(18, 18, 18)
                        .addComponent(jBsiguiente)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBnuevo)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBactualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBregistrar)
                                .addGap(36, 36, 36)
                                .addComponent(jBborrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLid_chofer)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLnombre)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLlicencia)
                            .addComponent(jTlicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLseguro)
                            .addComponent(jTseguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdomicilio)
                            .addComponent(jTdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLtelefono)
                            .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLedad)
                    .addComponent(jTedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtarjeton)
                    .addComponent(jTtarjeton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLasign)
                    .addComponent(jTasign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBatras)
                    .addComponent(jBatraspag)
                    .addComponent(jBsigPag)
                    .addComponent(jBsiguiente))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevo)
                    .addComponent(jBregistrar)
                    .addComponent(jBborrar))
                .addGap(18, 18, 18)
                .addComponent(jBactualizar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed

    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jBregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBregistrarMouseClicked
        String nombre;
        String licencia;
        String seguro;
        String domicilio;
        String telefono;
        String edad;
        String tarjeton;
        String asign;
        String id_chofer;

        try {
            id_chofer = this.jTid.getText();
            nombre = this.jTnombre.getText();
            licencia = this.jTlicencia.getText();
            seguro = this.jTseguro.getText();
            domicilio = this.jTdomicilio.getText();
            telefono = this.jTtelefono.getText();
            edad = this.jTedad.getText();
            tarjeton = this.jTtarjeton.getText();
            asign = this.jTasign.getText();

            String sql = "insert into chofer(nombre,licencia,seguro,domicilio,telefono,edad,tarjeton,asign) values ('" + nombre + "','" + licencia + "','" + seguro + "','" + domicilio + "','" + telefono + "','" + edad + "','" + tarjeton + "','" + asign + "');";
            System.out.println(sql);
            st.executeUpdate(sql);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos" + err.getLocalizedMessage());
        }
    }//GEN-LAST:event_jBregistrarMouseClicked

    private void jBatrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBatrasMouseClicked
        try {
            rs.first();

            if (rs.isLast() == false) {
                rs.first();
                
                this.jTid.setText(rs.getString("id_chofer"));
                this.jTnombre.setText(rs.getString("nombre"));
                this.jTlicencia.setText(rs.getString("licencia"));
                this.jTseguro.setText(rs.getString("seguro"));
                this.jTdomicilio.setText(rs.getString("domicilio"));
                this.jTtelefono.setText(rs.getString("telefono"));
                this.jTedad.setText(rs.getString("edad"));
                this.jTtarjeton.setText(rs.getString("tarjeton"));
                this.jTasign.setText(rs.getString("asign"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }


    }//GEN-LAST:event_jBatrasMouseClicked

    private void jBborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBborrarMouseClicked

        try {
            st.executeUpdate("delete from chofer where id_chofer=" + this.jTid.getText());

            this.primerRegistro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }


    }//GEN-LAST:event_jBborrarMouseClicked

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBatrasActionPerformed

    private void jBatraspagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBatraspagMouseClicked
        try {
            rs.previous();

            if (rs.isLast() == false) {
                rs.previous();
                this.jTid.setText(rs.getString("id_chofer"));
                this.jTnombre.setText(rs.getString("nombre"));
                this.jTlicencia.setText(rs.getString("licencia"));
                this.jTseguro.setText(rs.getString("seguro"));
                this.jTdomicilio.setText(rs.getString("domicilio"));
                this.jTtelefono.setText(rs.getString("telefono"));
                this.jTedad.setText(rs.getString("edad"));
                this.jTtarjeton.setText(rs.getString("tarjeton"));
                this.jTasign.setText(rs.getString("asign"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }

    }//GEN-LAST:event_jBatraspagMouseClicked

    private void jBsigPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsigPagMouseClicked
        try {
            rs.next();

            if (rs.isLast() == false) {
                rs.next();
                this.jTid.setText(rs.getString("id_chofer"));
                this.jTnombre.setText(rs.getString("nombre"));
                this.jTlicencia.setText(rs.getString("licencia"));
                this.jTseguro.setText(rs.getString("seguro"));
                this.jTdomicilio.setText(rs.getString("domicilio"));
                this.jTtelefono.setText(rs.getString("telefono"));
                this.jTedad.setText(rs.getString("edad"));
                this.jTtarjeton.setText(rs.getString("tarjeton"));
                this.jTasign.setText(rs.getString("asign"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }

    }//GEN-LAST:event_jBsigPagMouseClicked

    private void jBsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsiguienteMouseClicked
        try {
            rs.last();

            if (rs.isLast() == false) {
                rs.last();
                this.jTid.setText(rs.getString("id_chofer"));
                this.jTnombre.setText(rs.getString("nombre"));
                this.jTlicencia.setText(rs.getString("licencia"));
                this.jTseguro.setText(rs.getString("seguro"));
                this.jTdomicilio.setText(rs.getString("domicilio"));
                this.jTtelefono.setText(rs.getString("telefono"));
                this.jTedad.setText(rs.getString("edad"));
                this.jTtarjeton.setText(rs.getString("tarjeton"));
                this.jTasign.setText(rs.getString("asign"));
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }

    }//GEN-LAST:event_jBsiguienteMouseClicked

    private void jBnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBnuevoMouseClicked
        jTid.setText(null);
        jTnombre.setText(null);
        jTlicencia.setText(null);
        jTseguro.setText(null);
        jTdomicilio.setText(null);
        jTtelefono.setText(null);
        jTedad.setText(null);
        jTtarjeton.setText(null);
        jTasign.setText(null);
    }//GEN-LAST:event_jBnuevoMouseClicked

    private void jBactualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBactualizarMouseClicked
        
        String nombre;
        String licencia;
        String seguro;
        String domicilio;
        String telefono;
        String edad;
        String tarjeton;
        String asign;
        String id_chofer;

        try {
            id_chofer = this.jTid.getText();
            nombre = this.jTnombre.getText();
            licencia = this.jTlicencia.getText();
            seguro = this.jTseguro.getText();
            domicilio = this.jTdomicilio.getText();
            telefono = this.jTtelefono.getText();
            edad = this.jTedad.getText();
            tarjeton = this.jTtarjeton.getText();
            asign = this.jTasign.getText();

            st.executeUpdate("update chofer set nombre='" + nombre + "', licencia='" + licencia + "',seguro='" + seguro + "',domicilio= '" + domicilio + "',telefono= '" + telefono + "',edad= '" + edad + "',tarjeton= '" + tarjeton + "',asign= '" + asign + "' where id_chofer=" + this.jTid.getText());

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos" + err.getLocalizedMessage());
        }
        
      
    }
    
        /*else{

        metodosbd.Actualizar(jTnombre.getText(), jTlicencia.getText(), jTseguro.getText(),
                jTdomicilio.getText(), jTtelefono.getText(), jTedad.getSelectedItem().toString(),
                idcontacto);
    }//GEN-LAST:event_jBactualizarMouseClicked

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                



}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addchofer.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addchofer.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addchofer.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addchofer.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addchofer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jBatraspag;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JButton jBsigPag;
    private javax.swing.JButton jBsiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLasign;
    private javax.swing.JLabel jLdomicilio;
    private javax.swing.JLabel jLedad;
    private javax.swing.JLabel jLid_chofer;
    private javax.swing.JLabel jLlicencia;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLseguro;
    private javax.swing.JLabel jLtarjeton;
    private javax.swing.JLabel jLtelefono;
    private javax.swing.JTextField jTasign;
    private javax.swing.JTextField jTdomicilio;
    private javax.swing.JTextField jTedad;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTlicencia;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTseguro;
    private javax.swing.JTextField jTtarjeton;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables

    private void primerRegistro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
